# Generated by Django 5.2.17 on 2026-09-03 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi lista', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('compartida_con', models.ManyToManyField(blank=True, related_name='listas_compartidas', to=settings.AUTH_USER_MODEL)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('lista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='compras.listacompra')),
            ],
            options={
                'unique_together': {('lista', 'producto')},
            },
        ),
    ]
